export const GET_GENERAL_INFO_REPO = 'GET_GENERAL_INFO_REPO';
export const GET_FILE_DATA = 'GET_FILE_DATA';
export const GET_COMMIT_DATA = 'GET_COMMIT_DATA';
export const GET_COMMIT_DETAILS = 'GET_COMMIT_DETAILS';
export const UPDATE_PATH_TO_FILE = 'UPDATE_PATH_TO_FILE';
export const UPDATE_AUTH_STATE = 'UPDATE_AUTH_STATE';
export const SET_LIST_OF_BRANCHES = 'SET_LIST_OF_BRANCHES';
// projects
export const UPDATE_PROJECTS_LIST = 'UPDATE_PROJECTS_LIST';
export const SET_PROJECT_USERS = 'SET_PROJECT_USERS';
export const SET_ALL_PROJECTS = 'SET_ALL_PROJECTS';
export const SET_STARRED_PROJECTS = 'SET_STARRED_PROJECTS';
export const SET_USER_PROJECTS = 'SET_USER_PROJECTS';
export const SET_DATA_PROJECTS = 'SET_DATA_PROJECTS';
export const SET_CODE_PROJECTS = 'SET_CODE_PROJECTS';
export const SET_PROJECT_STARRERS = 'SET_PROJECT_STARRERS';
export const GET_LIST_OF_PROJECTS = 'GET_LIST_OF_PROJECTS';
export const SET_SELECTED_PROJECT = 'SET_SELECTED_PROJECT';
export const SET_PAGINATION_INFO = 'SET_PAGINATION_INFO';
export const SET_PROJECT_PIPES = 'SET_PROJECT_PIPES';

/*
 * ---------- Jobs and mrs ----------
*/
export const GET_JOBS = 'GET_JOBS';
export const GET_MERGE_REQUESTS = 'GET_MERGE_REQUESTS';
export const SET_MERGE_REQUEST = 'SET_MERGE_REQUEST';
// user, account, profile
export const SET_USER_INFO = 'SET_USER_INFO';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_META = 'UPDATE_USER_META';
export const UPDATE_USER_INSTRUCTIONS = 'UPDATE_USER_INSTRUCTIONS';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_PRECONFIGURED_OPERATIONS = 'SET_PRECONFIGURED_OPERATIONS';
export const SET_USER_INSPECTED_PROFILE = 'SET_USERS_PROFILE';
// actionModal
export const ACTION_MODAL_SET_VALUES = 'ACTION_MODAL_SET_VALUES';
export const ACTION_MODAL_RESET_STATE = 'ACTION_MODAL_RESET_STATE';
// groups
export const GET_USER_GROUPS = 'GET_USER_GROUPS';
// color marker
export const SET_GLOBAL_COLOR_MARKER = 'SET_GLOBAL_COLOR_MARKER';
export const SET_OPERATIONS = 'SET_OPERATIONS';
export const SET_ALGORITHMS = 'SET_ALGORITHMS';
export const SET_VISUALIZATIONS = 'SET_VISUALIZATIONS';
export const SET_IS_LOADING = 'SET_IS_LOADING';
// tutorial
export const TUTORIAL_TOGGLE = 'TUTORIAL_TOGGLE';
export const TUTORIAL_SET_ACTIVE = 'TUTORIAL_SET_ACTIVE';
export const TUTORIAL_SET_CURRENT = 'TUTORIAL_SET_CURRENT';
export const TUTORIAL_UPDATE_CURRENT = 'TUTORIAL_UPDATE_CURRENT';
export const TUTORIAL_ADD_STATUS_TO_RECORDS = 'TUTORIAL_ADD_STATUS_TO_RECORDS';
export const TUTORIAL_REMOVE_STATUS_FROM_RECORDS = 'TUTORIAL_REMOVE_STATUS_FROM_RECORDS';
export const TUTORIAL_UPDATE_STATUS_FROM_RECORDS = 'TUTORIAL_UPDATE_STATUS_FROM_RECORDS';
// errors
export const SET_ERROR_STATUS = 'SET_ERROR_STATUS';
