export const SET_LIST_OF_BRANCHES = 'SET_LIST_OF_BRANCHES';
// projects
export const SET_PROJECT_USERS = 'SET_PROJECT_USERS';
export const SET_PROJECT_STARRERS = 'SET_PROJECT_STARRERS';
export const GET_LIST_OF_PROJECTS = 'GET_LIST_OF_PROJECTS';
export const SET_SELECTED_PROJECT = 'SET_SELECTED_PROJECT';
export const SET_PROJECT_PIPES = 'SET_PROJECT_PIPES';
export const SET_DATAINSTANCES = 'SET_DATAINSTANCES';
export const SET_VISUALIZATIONS = 'SET_VISUALIZATIONS';

/*
 * ---------- Jobs and mrs ----------
*/
export const GET_JOBS = 'GET_JOBS';
export const GET_MERGE_REQUESTS = 'GET_MERGE_REQUESTS';
export const SET_MERGE_REQUEST = 'SET_MERGE_REQUEST';
// user, account, profile
export const SET_USER_INFO = 'SET_USER_INFO';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_META = 'UPDATE_USER_META';
export const UPDATE_USER_INSTRUCTIONS = 'UPDATE_USER_INSTRUCTIONS';
export const RESET_USER_INSTRUCTIONS = 'RESET_USER_INSTRUCTIONS';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_USER_INSPECTED_PROFILE = 'SET_USERS_PROFILE';
// actionModal
export const ACTION_MODAL_SET_VALUES = 'ACTION_MODAL_SET_VALUES';
export const ACTION_MODAL_RESET_STATE = 'ACTION_MODAL_RESET_STATE';
// groups
export const GET_USER_GROUPS = 'GET_USER_GROUPS';
// color marker
export const SET_GLOBAL_COLOR_MARKER = 'SET_GLOBAL_COLOR_MARKER';
export const SET_IS_LOADING = 'SET_IS_LOADING';
// tutorial
export const TUTORIAL_TOGGLE = 'TUTORIAL_TOGGLE';
export const TUTORIAL_SET_ACTIVE = 'TUTORIAL_SET_ACTIVE';
export const TUTORIAL_SET_CURRENT = 'TUTORIAL_SET_CURRENT';
export const TUTORIAL_UPDATE_CURRENT = 'TUTORIAL_UPDATE_CURRENT';
export const TUTORIAL_ADD_STATUS_TO_RECORDS = 'TUTORIAL_ADD_STATUS_TO_RECORDS';
export const TUTORIAL_REMOVE_STATUS_FROM_RECORDS = 'TUTORIAL_REMOVE_STATUS_FROM_RECORDS';
export const TUTORIAL_UPDATE_STATUS_FROM_RECORDS = 'TUTORIAL_UPDATE_STATUS_FROM_RECORDS';
// experiments
export const EXPERIMENTS_SET_PROJECTS_GRAPHS = 'EXPERIMENTS_SET_PROJECTS_GRAPHS';
// errors
export const SET_ERROR_STATUS = 'SET_ERROR_STATUS';
