/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/5.3.1/userguide/multi_project_builds.html
 */
pluginManagement {
    resolutionStrategy {
        eachPlugin {
            when {
                requested.id.id == "kotlin2js" ->
                    useModule("org.jetbrains.kotlin:kotlin-gradle-plugin:${requested.version}")

                requested.id.id == "org.jetbrains.kotlin.frontend" ->
                    useModule("org.jetbrains.kotlin:kotlin-frontend-plugin:${requested.version}")

                requested.id.id == "kotlin-platform-common" -> {
                    println("using kotlin-platform-common")
                    useModule("org.jetbrains.kotlin:kotlin-gradle-plugin:${requested.version}")
                }
                requested.id.id == "kotlin-multiplatform" -> {
                    println("using kotlinx-multiplatform")
                    useModule("org.jetbrains.kotlin:kotlin-gradle-plugin:${requested.version}")
                }
                requested.id.id == "kotlinx-serialization" -> {
                    println("using kotlinx-serialization")
                    useModule("org.jetbrains.kotlin:kotlin-serialization:${requested.version}")
                }
            }
        }
    }

    repositories {
        gradlePluginPortal()
        jcenter()
        maven { setUrl("https://jcenter.bintray.com/") }
        maven { setUrl("https://dl.bintray.com/kotlin/kotlin-eap") }
    }
}

rootProject.name = "mlreef-frontend"
// include("gitlabapi")
include("web")
