@startuml
actor User
participant Frontend
participant Backend
participant Gitlab

User -> Frontend: Sends username and password
activate Frontend
Frontend -> Backend: Sends username and password
activate Backend
Backend -> Backend: check for existing username
Backend -> Gitlab: test Token for validity
Frontend <- Backend: return stored Token
deactivate Backend
Frontend -> Frontend: cache Token as "Session"
User <- Frontend: display success
deactivate Frontend
@enduml