import React from 'react';
import { string, bool, func } from 'prop-types';
import '../../css/genericModal.css';

const DataInstanteDeleteModal = (props) => {
  const {
    isModalVisible,
    setIsVisible,
    typeOfMessage,
    onPositiveAction,
  } = props;

  const handlePositiveAction = (e) => {
    onPositiveAction(e);
    setIsVisible(false);
  };

  return isModalVisible && (
    <div>
      <div className="generic-modal">
        <div className="modal-content" style={{ height: '40%', minHeight: 250 }}>
          <div className="title" style={{ backgroundColor: '#f5544d', color: 'white' }}>
            <div style={{ padding: '0 3em' }}>
              <p>
                {
                  typeOfMessage === 'delete'
                    ? 'Delete dataset from your data pipeline: Data_pipeline_2'
                    : 'Abort creation of di_Data_Pipeline_2'
                }
              </p>
            </div>
            <div id="x-button-div">
              <button
                type="button"
                style={{
                  backgroundColor: '#f5544d',
                  border: 'none',
                  color: 'white',
                }}
                onClick={() => setIsVisible(false)}
              >
                <b>X</b>
              </button>
            </div>
          </div>
          <div style={{ textAlign: 'center', height: '65%' }}>
            {typeOfMessage === 'delete'
              ? (
                <>
                  <br />
                  <p>
                    <b>
                      Are you sure you want to delete your dataset: Data_pipeline_2
                    </b>
                  </p>
                  <p>
                    You will free
                    {' '}
                    <b>23 GB</b>
                    {' '}
                    of cloud storage.
                  </p>
                  <p>
                    You will loose all files generated by the pipeline
                  </p>
                </>
              )
              : (
                <>
                  <br />
                  <p>
                    <b>
                      Are you sure you want to abort the
                      creation of the dataset: di_data_pipeline_2
                    </b>
                  </p>
                  <p>
                    the task t_code will be aborted, all the progress will be lost
                  </p>
                  <div style={{ margin: '0px 3em' }}>
                    <p style={{ textAlign: 'left' }}>
                      Dataset:
                      <b>DI_ProjectName_1</b>
                    </p>
                    <div style={{
                      backgroundColor: 'white',
                      height: '2em',
                      borderRadius: '0.5em',
                      border: '0.4px solid #32AFC3',
                    }}
                    >
                      <div
                        id="progress-bar"
                        style={{
                          backgroundColor: '#32afc3',
                          height: '100%',
                          width: '40%',
                          borderRadius: 'inherit',
                        }}
                      />
                    </div>
                    <div style={{ display: 'flex' }}>
                      <div style={{ width: '50%', display: 'inherit', alignContent: '' }}>
                        <p style={{ fontSize: '0.8em', width: '100%', textAlign: 'start' }}>Loading files...</p>
                      </div>
                      <div style={{ width: '50%', display: 'inherit', alignContent: '' }}>
                        <p style={{ fontSize: '0.8em', width: '90%', textAlign: 'end' }}>ETA: 12min 45sec</p>
                      </div>
                    </div>
                  </div>
                </>
              )}
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between', padding: '0px 3em' }}>
            <button
              type="button"
              onClick={() => setIsVisible(false)}
              className="white-button"
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={handlePositiveAction}
              style={{
                backgroundColor: '#f5544d',
                color: 'white',
                padding: '0px 3em',
                borderRadius: '0.3vw',
                border: 'none',
              }}
            >
              {typeOfMessage === 'delete' ? 'Delete' : 'Abort'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

DataInstanteDeleteModal.defaultProps = {
  onPositiveAction: (x) => x,
};

DataInstanteDeleteModal.propTypes = {
  isModalVisible: bool.isRequired,
  setIsVisible: func.isRequired,
  onPositiveAction: func,
  typeOfMessage: string,
};

DataInstanteDeleteModal.defaultProps = {
  typeOfMessage: 'delete',
};

export default DataInstanteDeleteModal;
