type PublishingStatuses =
  "PUBLISH_CREATION_FAIL" |
  "PUBLISH_CREATED" |
  "PUBLISH_PENDING" |
  "PUBLISH_STARTING" |
  "PUBLISH_STARTED" |
  "PUBLISH_FINISHING" |
  "PUBLISHED" |
  "PUBLISH_FAILED" |
  "INCONSISTENT" |
  "OUTDATED" |
  "PIPELINE_MISSING" |
  "UNPUBLISH_CREATION_FAIL" |
  "UNPUBLISH_CREATED" |
  "UNPUBLISH_PENDING" |
  "UNPUBLISH_STARTING" |
  "UNPUBLISH_STARTED" |
  "UNPUBLISH_FINISHING" |
  "UNPUBLISHED" |
  "UNPUBLISH_FAILED" |
  "OTHER" |
  "REPUBLISH";

export default PublishingStatuses;
