export enum PROJECT_DATA_TYPES {
  ANY = 'ANY',
  AUDIO = 'AUDIO',
  BINARY = 'BINARY',
  NONE = 'NONE',
  HIERARCHICAL = 'HIERARCHICAL',
  IMAGE = 'IMAGE',
  TABULAR = 'TABULAR',
  TEXT = 'TEXT',
  TIME_SERIES = 'TIME_SERIES',
  VIDEO = 'VIDEO',
  MODEL = 'MODEL',
  NUMBER = 'NUMBER',
}