import React from 'react';
import {
  string,
} from 'prop-types';

const DataInstanteDeleteModal = (props) => {
  const {
    dataInstanceName,
  } = props;

  return (
    <>
      <p style={{ textAlign: 'center' }}>
        Are you sure you want to delete your dataset:
        {' '}
        <b>
          {dataInstanceName}
        </b>
      </p>
      <p style={{ textAlign: 'center' }}>
        You will loose all files generated by the pipeline
      </p>
    </>
  );
};

DataInstanteDeleteModal.propTypes = {
  dataInstanceName: string.isRequired,
};

export default DataInstanteDeleteModal;
