const classifiedMockedDatainstances = [
  {
    status: 'running',
    values: [
      {
        id: 91,
        status: 'running',
        name: 'data-pipeline/fit-dolphin-18012021215828-1',
        authorName: 'mlreef',
        createdAt: '2021-01-18T21:58:53.000+00:00',
        commit: {
          id: '394f5ce3b04aa68d81ff2a776a913b9da2b5e6cf',
          short_id: '394f5ce3',
          created_at: '2021-01-18T21:58:53.000+00:00',
          parent_ids: null,
          title: 'Add pipeline results [skip ci]',
          message: 'Add pipeline results [skip ci]',
          author_name: 'mlreef',
          author_email: 'mlreef@example.org',
          authored_date: '2021-01-18T21:58:53.000+00:00',
          committer_name: 'mlreef',
          committer_email: 'mlreef@example.org',
          committed_date: '2021-01-18T21:58:53.000+00:00',
        },
        backendPipeline: {
          id: 'a3fe17ee-8e45-4231-b442-1d1acb142df4',
          pipeline_type: 'DATA',
          data_project_id: '5d005488-afb6-4a0c-852a-f471153a04b5',
          slug: 'data-pipeline-fit-dolphin-18012021215828',
          name: 'data-pipeline/fit-dolphin-18012021215828',
          source_branch: 'master',
          target_branch_pattern: 'data-pipeline/fit-dolphin-18012021215828-$NUMBER',
          data_operations: [
            {
              slug: 'commons-create-thumbnails',
              parameters: [
                {
                  name: 'input-path',
                  value: 'data',
                  type: 'STRING',
                  required: true,
                  description: 'Data input, path to the images used for transformation',
                },
                {
                  name: 'output-path',
                  value: '.',
                  type: 'STRING',
                  required: true,
                  description: 'output directory to save images',
                },
                {
                  name: 'size',
                  value: '128',
                  type: 'INTEGER',
                  required: false,
                  description: 'size of thumbnail width = height',
                },
              ],
              id: '1309e9f1-187d-4710-a612-022f72ef99f3',
              name: 'Create Thumbnaills',
            },
          ],
          input_files: [
            {
              location: 'data',
              location_type: 'PATH_FOLDER',
            },
          ],
          instances: [
            {
              id: 'c34da493-5965-48a6-ba90-cfcbd2825601',
              pipeline_type: 'DATA',
              pipeline_config_id: 'a3fe17ee-8e45-4231-b442-1d1acb142df4',
              data_project_id: '5d005488-afb6-4a0c-852a-f471153a04b5',
              slug: 'data-pipeline-fit-dolphin-18012021215828-1',
              name: 'data-pipeline/fit-dolphin-18012021215828',
              source_branch: 'master',
              target_branch: 'data-pipeline/fit-dolphin-18012021215828-1',
              data_operations: [
                {
                  slug: 'commons-create-thumbnails',
                  parameters: [
                    {
                      name: 'input-path',
                      value: 'data',
                      type: 'STRING',
                      required: true,
                      description: 'Data input, path to the images used for transformation',
                    },
                    {
                      name: 'output-path',
                      value: '.',
                      type: 'STRING',
                      required: true,
                      description: 'output directory to save images',
                    },
                    {
                      name: 'size',
                      value: '128',
                      type: 'INTEGER',
                      required: false,
                      description: 'size of thumbnail width = height',
                    },
                  ],
                  id: '84412e5a-1cd6-488a-b11d-36df104d5def',
                  name: 'Create Thumbnaills',
                },
              ],
              input_files: [
                {
                  location: 'data',
                  location_type: 'PATH_FOLDER',
                },
              ],
              number: 1,
              commit: null,
              status: 'SUCCESS',
              pipeline_job_info: {
                id: 91,
                ref: 'data-pipeline/fit-dolphin-18012021215828-1',
                commit_sha: '5181b255c631bfa4ffbeb58d9a076b06e8dae1ae',
                created_at: '2021-01-18T21:58:39.578Z',
                updated_at: '2021-01-18T21:58:39.715Z',
                finished_at: '2021-01-18T21:59:23.441Z',
              },
            },
          ],
          dataInstanceId: 'c34da493-5965-48a6-ba90-cfcbd2825601',
        },
      },
    ],
  },
  {
    status: 'success',
    values: [],
  },
  {
    status: 'canceled',
    values: [],
  },
  {
    status: 'failed',
    values: [
      {
        id: 94,
        status: 'failed',
        name: 'data-pipeline/gentle-warwhal-18012021223245-1',
        authorName: 'mlreef',
        createdAt: '2021-01-18T22:33:03.000+00:00',
        commit: {
          id: '9a37890e25af2f26264a2907c25a8146237d94f7',
          short_id: '9a37890e',
          created_at: '2021-01-18T22:33:03.000+00:00',
          parent_ids: null,
          title: 'Add pipeline results [skip ci]',
          message: 'Add pipeline results [skip ci]',
          author_name: 'mlreef',
          author_email: 'mlreef@example.org',
          authored_date: '2021-01-18T22:33:03.000+00:00',
          committer_name: 'mlreef',
          committer_email: 'mlreef@example.org',
          committed_date: '2021-01-18T22:33:03.000+00:00',
        },
        backendPipeline: {
          id: '66df3da0-ea13-41e7-8f75-f75d5b46b515',
          pipeline_type: 'DATA',
          data_project_id: '5d005488-afb6-4a0c-852a-f471153a04b5',
          slug: 'data-pipeline-gentle-warwhal-18012021223245',
          name: 'data-pipeline/gentle-warwhal-18012021223245',
          source_branch: 'master',
          target_branch_pattern: 'data-pipeline/gentle-warwhal-18012021223245-$NUMBER',
          data_operations: [
            {
              slug: 'commons-color-modifier',
              parameters: [
                {
                  name: 'input-path',
                  value: 'data',
                  type: 'STRING',
                  required: true,
                  description: 'Data input, path to the images used for transformation',
                },
                {
                  name: 'output-path',
                  value: '.',
                  type: 'STRING',
                  required: true,
                  description: 'output directory to save images',
                },
                {
                  name: 'brightness',
                  value: '0.5',
                  type: 'FLOAT',
                  required: false,
                  description: 'Brightness value',
                },
                {
                  name: 'contrast',
                  value: '0.5',
                  type: 'FLOAT',
                  required: false,
                  description: 'contrast value',
                },
                {
                  name: 'saturation',
                  value: '2',
                  type: 'FLOAT',
                  required: false,
                  description: 'saturation value',
                },
              ],
              id: 'e0505e2b-3749-47f8-afda-283383f514ee',
              name: 'Color modifier',
            },
          ],
          input_files: [
            {
              location: 'data',
              location_type: 'PATH_FOLDER',
            },
          ],
          instances: [
            {
              id: '59159554-393d-4c0a-afd7-32c8c575432f',
              pipeline_type: 'DATA',
              pipeline_config_id: '66df3da0-ea13-41e7-8f75-f75d5b46b515',
              data_project_id: '5d005488-afb6-4a0c-852a-f471153a04b5',
              slug: 'data-pipeline-gentle-warwhal-18012021223245-1',
              name: 'data-pipeline/gentle-warwhal-18012021223245',
              source_branch: 'master',
              target_branch: 'data-pipeline/gentle-warwhal-18012021223245-1',
              data_operations: [
                {
                  slug: 'commons-color-modifier',
                  parameters: [
                    {
                      name: 'input-path',
                      value: 'data',
                      type: 'STRING',
                      required: true,
                      description: 'Data input, path to the images used for transformation',
                    },
                    {
                      name: 'output-path',
                      value: '.',
                      type: 'STRING',
                      required: true,
                      description: 'output directory to save images',
                    },
                    {
                      name: 'brightness',
                      value: '0.5',
                      type: 'FLOAT',
                      required: false,
                      description: 'Brightness value',
                    },
                    {
                      name: 'contrast',
                      value: '0.5',
                      type: 'FLOAT',
                      required: false,
                      description: 'contrast value',
                    },
                    {
                      name: 'saturation',
                      value: '2',
                      type: 'FLOAT',
                      required: false,
                      description: 'saturation value',
                    },
                  ],
                  id: 'b5e7a25e-e0a2-4e41-a5fd-62c1a990fc31',
                  name: 'Color modifier',
                },
              ],
              input_files: [
                {
                  location: 'data',
                  location_type: 'PATH_FOLDER',
                },
              ],
              number: 1,
              commit: null,
              status: 'SUCCESS',
              pipeline_job_info: {
                id: 94,
                ref: 'data-pipeline/gentle-warwhal-18012021223245-1',
                commit_sha: '1ab182a63edbdbb04c9b190860d29f4215c52afc',
                created_at: '2021-01-18T22:32:50.846Z',
                updated_at: '2021-01-18T22:32:50.936Z',
                finished_at: '2021-01-18T22:33:33.532Z',
              },
            },
          ],
          dataInstanceId: '59159554-393d-4c0a-afd7-32c8c575432f',
        },
      },
    ],
  },
  {
    status: 'expired',
    values: [],
  },
];

export default classifiedMockedDatainstances;
