export const dataProcessors = [{
  id: 'bc65cfbf-c09c-40ec-8bd5-d984ceb0e8b1',
  slug: 'ocr-with-tesseract',
  url: 'http://gitlab.review-master-8dyme2.35.246.253.255.nip.io/mlreef/ocr-with-tesseract',
  owner_id: 'aaaa0000-0001-0000-0000-cccccccccccc',
  name: 'OCR with tesseract',
  gitlab_namespace: 'mlreef',
  gitlab_path: 'ocr-with-tesseract',
  gitlab_id: 1370,
  visibility_scope: 'PUBLIC',
  description: 'Decode images to text using pytesseract',
  tags: [],
  stars_count: 0,
  forks_count: 0,
  input_data_types: [],
  output_data_types: [],
  searchable_type: 'CODE_PROJECT',
  processorSelected: 0,
  processors: [
    {
      id: '110dce76-d28d-4350-988a-af7b40e550b0',
      slug: 'ocr-with-tesseract',
      name: 'OCR with tesseract Processor',
      input_data_type: [],
      output_data_type: [],
      type: 'OPERATION',
      visibility_scope: 'PUBLIC',
      description: 'OCR with pytesseract for english and german only',
      code_project_id: 'bc65cfbf-c09c-40ec-8bd5-d984ceb0e8b1',
      author_id: 'aaaa0000-0001-0000-0000-cccccccccccc',
      branch: 'master',
      version: '2',
      publish_started_at: '2021-05-16T19:33:30.848Z',
      publish_finished_at: '2021-05-16T19:35:52.138Z',
      status: 'PUBLISHED',
      model_type: null,
      ml_category: null,
      environment: {
        id: '870a0b67-f36b-40c8-9e76-560c32d5f3e8',
        title: 'Base environment tensorflow/tensorflow:2.1.0-gpu-py3',
        docker_image: 'tensorflow/tensorflow:2.1.0-gpu-py3',
        description: 'GPU nvidia drivers and TF 2.1, compatible python 3.6-3.8',
        requirements: '                                Ubuntu 20.04\n                                python 3.6.9\n                                tensorflow-gpu 2.1.0\n                                CUDA 10.1\n                                CUDNN 7',
        machine_type: 'GPU',
        sdk_version: '3.6.9',
      },
      parameters: [
        {
          id: 'c5130a54-3fa9-4445-83ae-2769b872df08',
          name: 'lang',
          type: 'STRING',
          order: 3,
          default_value: 'eng',
          required: true,
          group: '',
          description: 'possible values eng or deu',
        },
        {
          id: 'ad3a7149-94c2-4462-b484-a22fab415bf7',
          name: 'input-path',
          type: 'STRING',
          order: 1,
          default_value: 'images',
          required: true,
          group: '',
          description: 'Path to the images',
        },
        {
          id: '3aefaeb4-f8cd-4a63-b12d-a3e99c30af8e',
          name: 'output-path',
          type: 'STRING',
          order: 2,
          default_value: 'output',
          required: true,
          group: '',
          description: 'Path to save the images',
        },
      ],
      metrics_schema: null,
    },
  ],
  published: true,
  processor_type: 'OPERATION',
},
];

export const selectedFiles = [
  {
    id: '3a2ee6399e40604e6dd5cfcf4b702363709ff718',
    name: 'train',
    type: 'tree',
    path: 'train',
    mode: '040000',
    checked: true,
    disabled: false,
  },
];
