export const dataProcessors = [
  {
    id: 'c471f1ed-54c6-4068-a8fd-fbfc86f99079',
    slug: 'add-noise-22feb',
    name: 'Add noise 22feb',
    inputDataType: 'IMAGE',
    outputDataType: 'IMAGE',
    type: 'OPERATION',
    visibilityScope: 'PRIVATE',
    description: 'description',
    codeProjectId: '6d8af6e2-131d-4836-97c1-f006db122d91',
    versions: [
      {
        id: 'e905e3d0-9866-4d59-8963-64e45a05aeb5',
        slug: 'add-noise-22feb',
        name: 'Add noise 22feb',
        input_data_type: 'IMAGE',
        output_data_type: 'IMAGE',
        type: 'OPERATION',
        visibility_scope: 'PRIVATE',
        description: 'description',
        code_project_id: '6d8af6e2-131d-4836-97c1-f006db122d91',
        data_processor_id: 'c471f1ed-54c6-4068-a8fd-fbfc86f99079',
        publisher_id: 'aaaa0000-0001-0000-0000-cccccccccccc',
        metric_type: 'UNDEFINED',
        parameters: [
          {
            name: 'input-path',
            type: 'STRING',
            required: true,
            order: 1,
            default_value: 'train',
            description: 'path to directory of images or image file',
          },
          {
            name: 'output-path',
            type: 'STRING',
            required: true,
            order: 2,
            default_value: 'output',
            description: 'output directory to save images',
          },
          {
            name: 'mode',
            type: 'STRING',
            required: true,
            order: 3,
            default_value: 'speckle',
            description: 'type of noise: gaussian , localvar , poisson , salt , pepper , speckle',
          },
        ],
        number: 1,
        branch: 'master',
        command: 'registry.review-master-8dyme2.35.246.253.255.nip.io/mlreef/add-noise-22feb:master',
        base_environment: {
          id: '870a0b67-f36b-40c8-9e76-560c32d5f3e8',
          title: 'Base environment tensorflow/tensorflow:2.1.0-gpu-py3',
          docker_image: 'tensorflow/tensorflow:2.1.0-gpu-py3',
          description: 'GPU nvidia drivers and TF 2.1, compatible python 3.6-3.8',
          requirements: '                                Ubuntu\n                                python3\n                                tensorflow-gpu 2.1.0\n                                CUDA 10.1\n                                CUDNN 7',
          machine_type: 'GPU',
          sdk_version: '3.6',
        },
        published_at: '2021-04-20T07:37:13.231Z',
      },
    ],
    parameters: [
      {
        name: 'input-path',
        type: 'STRING',
        required: true,
        order: 1,
        default_value: 'train',
        description: 'path to directory of images or image file',
        isValid: true,
        value: 'train',
      },
      {
        name: 'output-path',
        type: 'STRING',
        required: true,
        order: 2,
        default_value: 'output',
        description: 'output directory to save images',
        isValid: true,
        value: '.',
      },
      {
        name: 'mode',
        type: 'STRING',
        required: true,
        order: 3,
        default_value: 'speckle',
        description: 'type of noise: gaussian , localvar , poisson , salt , pepper , speckle',
        isValid: true,
        value: '.',
      },
    ],
    nameSpace: 'mlreef',
    inputDataTypes: [
      'IMAGE',
    ],
    stars: 1,
  },
];

export const selectedFiles = [
  {
    id: '3a2ee6399e40604e6dd5cfcf4b702363709ff718',
    name: 'train',
    type: 'tree',
    path: 'train',
    mode: '040000',
    checked: true,
    disabled: false,
  },
];
