export const imagesToRender = [
  {
    commitId: 'd80ab8ff15fb1f327bac0f5679b454cbec247759',
    parentCommitId: '6819ee9d2e8f7796887cc87af2d396c9894a2ebf',
    previousImage: {},
    nextImage: {},
    fileName: 'color_0_0054_A.png',
  },
];

export const mockMatchDataCommitDet = {
  path: '/my-projects/:projectId/commit/:commitId',
  url: '/my-projects/12395599/commit/aede036f526ea5d591f5ee56c131ed8472483912',
  isExact: true,
  params: {
    projectId: '12395599',
    branch: 'master',
    file: '.gitignore',
    commitId: 'aede036f526ea5d591f5ee56c131ed8472483912',
  },
};

export const commitMockObject = {
  id: 'd80ab8ff15fb1f327bac0f5679b454cbec247759',
  short_id: 'd80ab8ff',
  created_at: '2019-11-09T14:24:40.000Z',
  parent_ids: [
    '6819ee9d2e8f7796887cc87af2d396c9894a2ebf',
  ],
  title: 'Replace color_0_0054_A.png',
  message: 'Replace color_0_0054_A.png',
  author_name: 'cpmlreef',
  author_email: 'cp@mlreef.com',
  authored_date: '2019-11-09T14:24:40.000Z',
  committer_name: 'cpmlreef',
  committer_email: 'cp@mlreef.com',
  committed_date: '2019-11-09T14:24:40.000Z',
  stats: {
    additions: 0,
    deletions: 0,
    total: 0,
  },
  status: null,
  last_pipeline: null,
  project_id: 14448940,
};

export const mockDiffArray = [
  {
    old_path: 'showcase/color_0_0054_A.png',
    new_path: 'showcase/color_0_0054_A.png',
    a_mode: '100644',
    b_mode: '100644',
    new_file: false,
    renamed_file: false,
    deleted_file: false,
    diff: 'Binary files a/showcase/color_0_0054_A.png and b/showcase/color_0_0054_A.png differ\n',
  },
];

export const projectsArrayMock = {
  projects: {
    all: [
      {
        id: 14448940,
        description: 'Categorical Classification of alphabets in the American Sign Language',
        name: 'Sign Language Classifier',
        name_with_namespace: 'MLReef / Sign Language Classifier',
        path: 'sign-language-classifier',
        path_with_namespace: 'mlreef/sign-language-classifier',
        created_at: '2019-09-23T08:51:23.983Z',
        default_branch: 'master',
        tag_list: [],
        ssh_url_to_repo: 'git@gitlab.com:mlreef/sign-language-classifier.git',
        http_url_to_repo: 'https://gitlab.com/mlreef/sign-language-classifier.git',
        web_url: 'https://gitlab.com/mlreef/sign-language-classifier',
        readme_url: 'https://gitlab.com/mlreef/sign-language-classifier/blob/master/README.md',
        avatar_url: 'https://gitlab.com/uploads/-/system/project/avatar/14448940/proxy.duckduckgo.png',
        star_count: 0,
        forks_count: 0,
        last_activity_at: '2019-11-10T15:14:17.804Z',
        namespace: {
          id: 5351747,
          name: 'MLReef',
          path: 'mlreef',
          kind: 'group',
          full_path: 'mlreef',
          parent_id: null,
          avatar_url: '/uploads/-/system/group/avatar/5351747/MLReef_Logo_POS_H_icon-01.png',
          web_url: 'https://gitlab.com/groups/mlreef',
        },
      },
    ],
    selectedProject: {
      id: 12395599,
      description: 'This is MLReef´s demo repository.',
      name: 'demo',
      name_with_namespace: 'MLReef / demo',
      path: 'mlreef-demo',
      path_with_namespace: 'mlreef/mlreef-demo',
      created_at: '2019-05-18T09:34:29.346Z',
      default_branch: 'master',
      tag_list: [],
      ssh_url_to_repo: 'git@gitlab.com:mlreef/mlreef-demo.git',
      http_url_to_repo: 'https://gitlab.com/mlreef/mlreef-demo.git',
      web_url: 'https://gitlab.com/mlreef/mlreef-demo',
      readme_url: 'https://gitlab.com/mlreef/mlreef-demo/blob/master/README.md',
      avatar_url: 'https://gitlab.com/uploads/-/system/project/avatar/12395599/shutterstock_129655604-Converted-copy-text.png',
      star_count: 2,
      forks_count: 1,
      last_activity_at: '2019-11-11T10:36:06.189Z',
      namespace: {
        id: 5351747,
        name: 'MLReef',
        path: 'mlreef',
        kind: 'group',
        full_path: 'mlreef',
        parent_id: null,
        avatar_url: '/uploads/-/system/group/avatar/5351747/MLReef_Logo_POS_H_icon-01.png',
        web_url: 'https://gitlab.com/groups/mlreef',
      },
    },
  },
  users: [
    {
      id: 3839940,
      name: 'cpmlreef',
      username: 'cpmlreef',
      state: 'active',
      avatar_url: 'https://assets.gitlab-static.net/uploads/-/system/user/avatar/3839940/avatar.png',
      web_url: 'https://gitlab.com/cpmlreef',
    },
  ],
};


export const branchesMock = [
  {
    name: 'data-instance/664e1c60',
    commit: {
      id: '12e05078d142b2bee947e86d6a52db4a5f85eb65',
      short_id: '12e05078',
      created_at: '2019-11-01T21:08:23.000+00:00',
      parent_ids: null,
      title: 'Add pipeline results [skip ci]',
      message: 'Add pipeline results [skip ci]',
      author_name: 'mlreefdemo',
      author_email: 'rainer+mlreefdemo@systemkern.com',
      authored_date: '2019-11-01T21:08:23.000+00:00',
      committer_name: 'mlreefdemo',
      committer_email: 'rainer+mlreefdemo@systemkern.com',
      committed_date: '2019-11-01T21:08:23.000+00:00',
    },
    merged: false,
    protected: false,
    developers_can_push: false,
    developers_can_merge: false,
    can_push: true,
    default: false,
  },
  {
    name: 'data-instance/9ae9c8c0',
    commit: {
      id: '3e36bfab31a1d43457e00f46af9e6d31d4f55a66',
      short_id: '3e36bfab',
      created_at: '2019-11-14T20:32:52.000+00:00',
      parent_ids: null,
      title: 'Add pipeline results [skip ci]',
      message: 'Add pipeline results [skip ci]',
      author_name: 'mlreefdemo',
      author_email: 'rainer+mlreefdemo@systemkern.com',
      authored_date: '2019-11-14T20:32:52.000+00:00',
      committer_name: 'mlreefdemo',
      committer_email: 'rainer+mlreefdemo@systemkern.com',
      committed_date: '2019-11-14T20:32:52.000+00:00',
    },
    merged: false,
    protected: false,
    developers_can_push: false,
    developers_can_merge: false,
    can_push: true,
    default: false,
  },
  {
    name: 'master',
    commit: {
      id: '3e36bfab31a1d43457e00f46af9e6d31d4f55a66',
      short_id: '3e36bfab',
      created_at: '2019-11-14T20:32:52.000+00:00',
      parent_ids: null,
      title: 'Add pipeline results [skip ci]',
      message: 'Add pipeline results [skip ci]',
      author_name: 'mlreefdemo',
      author_email: 'rainer+mlreefdemo@systemkern.com',
      authored_date: '2019-11-14T20:32:52.000+00:00',
      committer_name: 'mlreefdemo',
      committer_email: 'rainer+mlreefdemo@systemkern.com',
      committed_date: '2019-11-14T20:32:52.000+00:00',
    },
    merged: false,
    protected: true,
    developers_can_push: false,
    developers_can_merge: false,
    can_push: true,
    default: true,
  },
];


export const mockMergeRequests = [
  {
    mrState: 'opened',
    list: [],
    length: 0,
  },
  {
    mrState: 'closed',
    list: [
      {
        id: 45076613,
        iid: 4,
        project_id: 14448940,
        title: 'asdasd',
        description: 'asdasd',
        state: 'closed',
        created_at: '2019-12-13T18:53:50.295Z',
        updated_at: '2020-01-08T04:43:39.182Z',
        merged_by: null,
        merged_at: null,
        closed_by: {
          id: 3839940,
          name: 'cpmlreef',
          username: 'cpmlreef',
          state: 'active',
          avatar_url: 'https://assets.gitlab-static.net/uploads/-/system/user/avatar/3839940/avatar.png',
          web_url: 'https://gitlab.com/cpmlreef',
        },
        closed_at: '2020-01-08T04:43:39.213Z',
        target_branch: 'banananan',
        source_branch: 'master',
        user_notes_count: 0,
        upvotes: 0,
        downvotes: 0,
        assignee: null,
        author: {
          id: 4462517,
          name: 'MLReef Demo',
          username: 'mlreefdemo',
          state: 'active',
          avatar_url: 'https://assets.gitlab-static.net/uploads/-/system/user/avatar/4462517/avatar.png',
          web_url: 'https://gitlab.com/mlreefdemo',
        },
        assignees: [],
        source_project_id: 14448940,
        target_project_id: 14448940,
        labels: [],
        work_in_progress: false,
        milestone: null,
        merge_when_pipeline_succeeds: false,
        merge_status: 'cannot_be_merged',
        sha: 'd80ab8ff15fb1f327bac0f5679b454cbec247759',
        merge_commit_sha: null,
        squash_commit_sha: null,
        discussion_locked: null,
        should_remove_source_branch: null,
        force_remove_source_branch: null,
        reference: '!4',
        references: {
          short: '!4',
          relative: '!4',
          full: 'mlreef/sign-language-classifier!4',
        },
        web_url: 'https://gitlab.com/mlreef/sign-language-classifier/merge_requests/4',
        time_stats: {
          time_estimate: 0,
          total_time_spent: 0,
          human_time_estimate: null,
          human_total_time_spent: null,
        },
        squash: false,
        task_completion_status: {
          count: 0,
          completed_count: 0,
        },
        has_conflicts: true,
        blocking_discussions_resolved: true,
        approvals_before_merge: null,
      },
      {
        id: 45063299,
        iid: 3,
        project_id: 14448940,
        title: 'test-mr',
        description: '',
        state: 'closed',
        created_at: '2019-12-13T16:29:47.017Z',
        updated_at: '2019-12-13T16:30:29.031Z',
        merged_by: null,
        merged_at: null,
        closed_by: {
          id: 4273308,
          name: 'Andres Ausecha',
          username: 'andres46',
          state: 'active',
          avatar_url: 'https://assets.gitlab-static.net/uploads/-/system/user/avatar/4273308/avatar.png',
          web_url: 'https://gitlab.com/andres46',
        },
        closed_at: '2019-12-13T16:30:29.043Z',
        target_branch: 'data-instance/f6e70e00',
        source_branch: 'master',
        user_notes_count: 0,
        upvotes: 0,
        downvotes: 0,
        assignee: null,
        author: {
          id: 4462517,
          name: 'MLReef Demo',
          username: 'mlreefdemo',
          state: 'active',
          avatar_url: 'https://assets.gitlab-static.net/uploads/-/system/user/avatar/4462517/avatar.png',
          web_url: 'https://gitlab.com/mlreefdemo',
        },
        assignees: [],
        source_project_id: 14448940,
        target_project_id: 14448940,
        labels: [],
        work_in_progress: false,
        milestone: null,
        merge_when_pipeline_succeeds: false,
        merge_status: 'cannot_be_merged',
        sha: 'd80ab8ff15fb1f327bac0f5679b454cbec247759',
        merge_commit_sha: null,
        squash_commit_sha: null,
        discussion_locked: null,
        should_remove_source_branch: null,
        force_remove_source_branch: null,
        reference: '!3',
        references: {
          short: '!3',
          relative: '!3',
          full: 'mlreef/sign-language-classifier!3',
        },
        web_url: 'https://gitlab.com/mlreef/sign-language-classifier/merge_requests/3',
        time_stats: {
          time_estimate: 0,
          total_time_spent: 0,
          human_time_estimate: null,
          human_total_time_spent: null,
        },
        squash: false,
        task_completion_status: {
          count: 0,
          completed_count: 0,
        },
        has_conflicts: true,
        blocking_discussions_resolved: true,
        approvals_before_merge: null,
      },
      {
        id: 44482488,
        iid: 2,
        project_id: 14448940,
        title: 'qwdqwdqwd',
        description: 'qwdqwdqwd',
        state: 'closed',
        created_at: '2019-12-07T18:52:41.702Z',
        updated_at: '2019-12-07T18:53:28.132Z',
        merged_by: null,
        merged_at: null,
        closed_by: {
          id: 4273308,
          name: 'Andres Ausecha',
          username: 'andres46',
          state: 'active',
          avatar_url: 'https://assets.gitlab-static.net/uploads/-/system/user/avatar/4273308/avatar.png',
          web_url: 'https://gitlab.com/andres46',
        },
        closed_at: '2019-12-07T18:53:28.154Z',
        target_branch: 'data-instance/f6e70e00',
        source_branch: 'master',
        user_notes_count: 0,
        upvotes: 0,
        downvotes: 0,
        assignee: null,
        author: {
          id: 4462517,
          name: 'MLReef Demo',
          username: 'mlreefdemo',
          state: 'active',
          avatar_url: 'https://assets.gitlab-static.net/uploads/-/system/user/avatar/4462517/avatar.png',
          web_url: 'https://gitlab.com/mlreefdemo',
        },
        assignees: [],
        source_project_id: 14448940,
        target_project_id: 14448940,
        labels: [],
        work_in_progress: false,
        milestone: null,
        merge_when_pipeline_succeeds: false,
        merge_status: 'cannot_be_merged',
        sha: 'd80ab8ff15fb1f327bac0f5679b454cbec247759',
        merge_commit_sha: null,
        squash_commit_sha: null,
        discussion_locked: null,
        should_remove_source_branch: null,
        force_remove_source_branch: null,
        reference: '!2',
        references: {
          short: '!2',
          relative: '!2',
          full: 'mlreef/sign-language-classifier!2',
        },
        web_url: 'https://gitlab.com/mlreef/sign-language-classifier/merge_requests/2',
        time_stats: {
          time_estimate: 0,
          total_time_spent: 0,
          human_time_estimate: null,
          human_total_time_spent: null,
        },
        squash: false,
        task_completion_status: {
          count: 0,
          completed_count: 0,
        },
        has_conflicts: true,
        blocking_discussions_resolved: true,
        approvals_before_merge: null,
      },
      {
        id: 44066953,
        iid: 1,
        project_id: 14448940,
        title: 'title',
        description: 'title desc',
        state: 'closed',
        created_at: '2019-12-05T21:31:30.388Z',
        updated_at: '2019-12-05T21:32:06.806Z',
        merged_by: null,
        merged_at: null,
        closed_by: {
          id: 4273308,
          name: 'Andres Ausecha',
          username: 'andres46',
          state: 'active',
          avatar_url: 'https://assets.gitlab-static.net/uploads/-/system/user/avatar/4273308/avatar.png',
          web_url: 'https://gitlab.com/andres46',
        },
        closed_at: '2019-12-05T21:32:06.883Z',
        target_branch: 'data-instance/f6e70e00',
        source_branch: 'master',
        user_notes_count: 0,
        upvotes: 0,
        downvotes: 0,
        assignee: null,
        author: {
          id: 4462517,
          name: 'MLReef Demo',
          username: 'mlreefdemo',
          state: 'active',
          avatar_url: 'https://assets.gitlab-static.net/uploads/-/system/user/avatar/4462517/avatar.png',
          web_url: 'https://gitlab.com/mlreefdemo',
        },
        assignees: [],
        source_project_id: 14448940,
        target_project_id: 14448940,
        labels: [],
        work_in_progress: false,
        milestone: null,
        merge_when_pipeline_succeeds: false,
        merge_status: 'cannot_be_merged',
        sha: 'd80ab8ff15fb1f327bac0f5679b454cbec247759',
        merge_commit_sha: null,
        squash_commit_sha: null,
        discussion_locked: null,
        should_remove_source_branch: null,
        force_remove_source_branch: null,
        reference: '!1',
        references: {
          short: '!1',
          relative: '!1',
          full: 'mlreef/sign-language-classifier!1',
        },
        web_url: 'https://gitlab.com/mlreef/sign-language-classifier/merge_requests/1',
        time_stats: {
          time_estimate: 0,
          total_time_spent: 0,
          human_time_estimate: null,
          human_total_time_spent: null,
        },
        squash: false,
        task_completion_status: {
          count: 0,
          completed_count: 0,
        },
        has_conflicts: true,
        blocking_discussions_resolved: true,
        approvals_before_merge: null,
      },
    ],
    length: 4,
  },
  {
    mrState: 'merged',
    list: [],
    length: 0,
  },
];
