const classifiedMockedVisualizations = [
  {
    status: 'running',
    values: [
      {
        id: 97,
        status: 'running',
        name: 'data-visualization/fresh-seal-18012021225907-2',
        authorName: 'mlreef',
        createdAt: '2021-01-18T22:59:12.000+00:00',
        commit: {
          id: '4b9dc8c8fabf9d68d3cb7ede07bc4a4bb1c83b8e',
          short_id: '4b9dc8c8',
          created_at: '2021-01-18T22:59:12.000+00:00',
          parent_ids: null,
          title: '[skip ci] create .mlreef.yml',
          message: '[skip ci] create .mlreef.yml',
          author_name: 'mlreef',
          author_email: 'mlreef@example.org',
          authored_date: '2021-01-18T22:59:12.000+00:00',
          committer_name: 'mlreef',
          committer_email: 'mlreef@example.org',
          committed_date: '2021-01-18T22:59:12.000+00:00',
        },
        backendPipeline: {
          id: 'b3b05d6b-d3ae-4c58-8bf9-ed7a47f34566',
          pipeline_type: 'VISUALIZATION',
          data_project_id: '5d005488-afb6-4a0c-852a-f471153a04b5',
          slug: 'data-visualization-fresh-seal-18012021225907',
          name: 'data-visualization/fresh-seal-18012021225907',
          source_branch: 'master',
          target_branch_pattern: 'data-visualization/fresh-seal-18012021225907-$NUMBER',
          data_operations: [
            {
              slug: 'commons-scatterplot',
              parameters: [
                {
                  name: 'input-path',
                  value: 'data',
                  type: 'STRING',
                  required: true,
                  description: 'Data input, path to the folder with the csv files',
                },
                {
                  name: 'output-path',
                  value: '.',
                  type: 'STRING',
                  required: true,
                  description: 'path to directory to save the scatter plots',
                },
                {
                  name: 'column-x',
                  value: '0',
                  type: 'INTEGER',
                  required: false,
                  description: 'Selects the csv column data to plot in axis x',
                },
                {
                  name: 'column-y',
                  value: '1',
                  type: 'INTEGER',
                  required: false,
                  description: 'Selects the csv column data to plot in axis y',
                },
                {
                  name: 'label-x',
                  value: 'x',
                  type: 'STRING',
                  required: false,
                  description: 'Label for axis x',
                },
                {
                  name: 'label-y',
                  value: 'y',
                  type: 'STRING',
                  required: false,
                  description: 'Label for axis x',
                },
                {
                  name: 'title',
                  value: 'Scatter plot x.vs y',
                  type: 'STRING',
                  required: false,
                  description: 'Title of plot',
                },
              ],
              id: 'd95b4edd-1b6c-4762-a87c-c877bd3c3d2f',
              name: 'Scatter Plot',
            },
          ],
          input_files: [
            {
              location: 'data',
              location_type: 'PATH_FOLDER',
            },
          ],
          instances: [
            {
              id: '3ddd103c-537d-479b-ba9d-1d6cfb2aed77',
              pipeline_type: 'VISUALIZATION',
              pipeline_config_id: 'b3b05d6b-d3ae-4c58-8bf9-ed7a47f34566',
              data_project_id: '5d005488-afb6-4a0c-852a-f471153a04b5',
              slug: 'data-visualization-fresh-seal-18012021225907-1',
              name: 'data-visualization/fresh-seal-18012021225907',
              source_branch: 'master',
              target_branch: 'data-visualization/fresh-seal-18012021225907-1',
              data_operations: [
                {
                  slug: 'commons-scatterplot',
                  parameters: [
                    {
                      name: 'input-path',
                      value: 'data',
                      type: 'STRING',
                      required: true,
                      description: 'Data input, path to the folder with the csv files',
                    },
                    {
                      name: 'output-path',
                      value: '.',
                      type: 'STRING',
                      required: true,
                      description: 'path to directory to save the scatter plots',
                    },
                    {
                      name: 'column-x',
                      value: '0',
                      type: 'INTEGER',
                      required: false,
                      description: 'Selects the csv column data to plot in axis x',
                    },
                    {
                      name: 'column-y',
                      value: '1',
                      type: 'INTEGER',
                      required: false,
                      description: 'Selects the csv column data to plot in axis y',
                    },
                    {
                      name: 'label-x',
                      value: 'x',
                      type: 'STRING',
                      required: false,
                      description: 'Label for axis x',
                    },
                    {
                      name: 'label-y',
                      value: 'y',
                      type: 'STRING',
                      required: false,
                      description: 'Label for axis x',
                    },
                    {
                      name: 'title',
                      value: 'Scatter plot x.vs y',
                      type: 'STRING',
                      required: false,
                      description: 'Title of plot',
                    },
                  ],
                  id: '3841eca2-9b0d-4f75-8bb3-570910c66eee',
                  name: 'Scatter Plot',
                },
              ],
              input_files: [
                {
                  location: 'data',
                  location_type: 'PATH_FOLDER',
                },
              ],
              number: 1,
              commit: null,
              status: 'SUCCESS',
              pipeline_job_info: {
                id: 97,
                ref: 'data-visualization/fresh-seal-18012021225907-1',
                commit_sha: '4b9dc8c8fabf9d68d3cb7ede07bc4a4bb1c83b8e',
                created_at: '2021-01-18T22:59:14.163Z',
                updated_at: '2021-01-18T22:59:14.266Z',
                finished_at: '2021-01-18T22:59:43.639Z',
              },
            },
          ],
          dataInstanceId: '3ddd103c-537d-479b-ba9d-1d6cfb2aed77',
        },
      },
    ],
  },
  {
    status: 'success',
    values: [],
  },
  {
    status: 'canceled',
    values: [],
  },
  {
    status: 'failed',
    values: [
      {
        id: 97,
        status: 'failed',
        name: 'data-visualization/fresh-seal-18012021225907-1',
        authorName: 'mlreef',
        createdAt: '2021-01-18T22:59:12.000+00:00',
        commit: {
          id: '4b9dc8c8fabf9d68d3cb7ede07bc4a4bb1c83b8e',
          short_id: '4b9dc8c8',
          created_at: '2021-01-18T22:59:12.000+00:00',
          parent_ids: null,
          title: '[skip ci] create .mlreef.yml',
          message: '[skip ci] create .mlreef.yml',
          author_name: 'mlreef',
          author_email: 'mlreef@example.org',
          authored_date: '2021-01-18T22:59:12.000+00:00',
          committer_name: 'mlreef',
          committer_email: 'mlreef@example.org',
          committed_date: '2021-01-18T22:59:12.000+00:00',
        },
        backendPipeline: {
          id: 'b3b05d6b-d3ae-4c58-8bf9-ed7a47f34566',
          pipeline_type: 'VISUALIZATION',
          data_project_id: '5d005488-afb6-4a0c-852a-f471153a04b5',
          slug: 'data-visualization-fresh-seal-18012021225907',
          name: 'data-visualization/fresh-seal-18012021225907',
          source_branch: 'master',
          target_branch_pattern: 'data-visualization/fresh-seal-18012021225907-$NUMBER',
          data_operations: [
            {
              slug: 'commons-scatterplot',
              parameters: [
                {
                  name: 'input-path',
                  value: 'data',
                  type: 'STRING',
                  required: true,
                  description: 'Data input, path to the folder with the csv files',
                },
                {
                  name: 'output-path',
                  value: '.',
                  type: 'STRING',
                  required: true,
                  description: 'path to directory to save the scatter plots',
                },
                {
                  name: 'column-x',
                  value: '0',
                  type: 'INTEGER',
                  required: false,
                  description: 'Selects the csv column data to plot in axis x',
                },
                {
                  name: 'column-y',
                  value: '1',
                  type: 'INTEGER',
                  required: false,
                  description: 'Selects the csv column data to plot in axis y',
                },
                {
                  name: 'label-x',
                  value: 'x',
                  type: 'STRING',
                  required: false,
                  description: 'Label for axis x',
                },
                {
                  name: 'label-y',
                  value: 'y',
                  type: 'STRING',
                  required: false,
                  description: 'Label for axis x',
                },
                {
                  name: 'title',
                  value: 'Scatter plot x.vs y',
                  type: 'STRING',
                  required: false,
                  description: 'Title of plot',
                },
              ],
              id: 'd95b4edd-1b6c-4762-a87c-c877bd3c3d2f',
              name: 'Scatter Plot',
            },
          ],
          input_files: [
            {
              location: 'data',
              location_type: 'PATH_FOLDER',
            },
          ],
          instances: [
            {
              id: '3ddd103c-537d-479b-ba9d-1d6cfb2aed77',
              pipeline_type: 'VISUALIZATION',
              pipeline_config_id: 'b3b05d6b-d3ae-4c58-8bf9-ed7a47f34566',
              data_project_id: '5d005488-afb6-4a0c-852a-f471153a04b5',
              slug: 'data-visualization-fresh-seal-18012021225907-1',
              name: 'data-visualization/fresh-seal-18012021225907',
              source_branch: 'master',
              target_branch: 'data-visualization/fresh-seal-18012021225907-1',
              data_operations: [
                {
                  slug: 'commons-scatterplot',
                  parameters: [
                    {
                      name: 'input-path',
                      value: 'data',
                      type: 'STRING',
                      required: true,
                      description: 'Data input, path to the folder with the csv files',
                    },
                    {
                      name: 'output-path',
                      value: '.',
                      type: 'STRING',
                      required: true,
                      description: 'path to directory to save the scatter plots',
                    },
                    {
                      name: 'column-x',
                      value: '0',
                      type: 'INTEGER',
                      required: false,
                      description: 'Selects the csv column data to plot in axis x',
                    },
                    {
                      name: 'column-y',
                      value: '1',
                      type: 'INTEGER',
                      required: false,
                      description: 'Selects the csv column data to plot in axis y',
                    },
                    {
                      name: 'label-x',
                      value: 'x',
                      type: 'STRING',
                      required: false,
                      description: 'Label for axis x',
                    },
                    {
                      name: 'label-y',
                      value: 'y',
                      type: 'STRING',
                      required: false,
                      description: 'Label for axis x',
                    },
                    {
                      name: 'title',
                      value: 'Scatter plot x.vs y',
                      type: 'STRING',
                      required: false,
                      description: 'Title of plot',
                    },
                  ],
                  id: '3841eca2-9b0d-4f75-8bb3-570910c66eee',
                  name: 'Scatter Plot',
                },
              ],
              input_files: [
                {
                  location: 'data',
                  location_type: 'PATH_FOLDER',
                },
              ],
              number: 1,
              commit: null,
              status: 'SUCCESS',
              pipeline_job_info: {
                id: 97,
                ref: 'data-visualization/fresh-seal-18012021225907-1',
                commit_sha: '4b9dc8c8fabf9d68d3cb7ede07bc4a4bb1c83b8e',
                created_at: '2021-01-18T22:59:14.163Z',
                updated_at: '2021-01-18T22:59:14.266Z',
                finished_at: '2021-01-18T22:59:43.639Z',
              },
            },
          ],
          dataInstanceId: '3ddd103c-537d-479b-ba9d-1d6cfb2aed77',
        },
      },
    ],
  },
  {
    status: 'expired',
    values: [],
  },
];

export default classifiedMockedVisualizations;
